<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="index.css" .css>
  <link rel="stylesheet" href="domu.css" .css>
  <title>Document</title>
  <script src="js_library/jquery-3.6.0.js"></script>
  <script src="js_library/scrollie/jquery.scrollie.min.js"></script>
  <script src="https://unpkg.com/aos@2.3.1/dist/aos.js" defer></script>
  <script>
    window.onload = () => {
      AOS.init({
        delay: 100, // values from 0 to 3000, with step 50ms
        duration: 1000,// values from 0 to 3000, with step 50ms
        offset: 50
      });
    };
  </script>
  <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
</head>

<body>

  <script src="index.js"></script>
  <div class="header">

    <div id="logo_media">
      <a href="index.html" class="logo"><img id="logo" src="spsei.svg" alt="logo"></a>
    </div>
    <div class="burger" onclick="funkce_burger(this)">
      <div class="bar1"></div>
      <div class="bar2"></div>
      <div class="bar3"></div>
    </div>
    <div class="header-left">
      <nav id="odkazy">
        <div>
        <a class="btn" href="index.html">Domů</a>
        <a class="btn" href="Half-Life.html">Half-Life</a>
        <a class="btn" href="#Half-Life">Half-Life 2</a>
        <a class="btn" href="#Half-Life">Half-Life 2 epizoda 1</a>
        <a class="btn" href="#Half-Life">Half-Life 2 epizoda 2</a>
        <a class="btn" href="#Half-Life">Half-Life: Alyx</a>
      </div>
        <div id="prihlaseni">
          <a id="prihlas" class="btn" href="#">Přihlásit se</a>
          <a id="registr" class="btn" href="#">Registrovat se</a>
        </div>
      </nav>
      
    </div>
  </div>
  