<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <title>Document</title>
  <script src="jquery-3.6.0.js"></script>

  <script src="https://unpkg.com/aos@2.3.1/dist/aos.js" defer></script>
  <script>
    window.onload = () => {
      AOS.init({
        delay: 100, // values from 0 to 3000, with step 50ms
        duration: 1000 // values from 0 to 3000, with step 50ms
      });
    };
  </script>
  <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
</head>


<h1 class="text-center">Half-Life</h1>
      <div class="container" >
      <div class=" card  text-black d-flex flex-column" style="background-color: #f1f1f1;">

        <h2 class="text-center">Co říká Wikipedie</h2>
        <div class="row">
        <div class="col d-flex">
          <div class="m-5" data-aos="fade-right">
          Half-Life (graficky znázorněno jako HλLF-LIFE) je akční počítačová hra ve stylu sci-fi FPS, vyvinutá firmou
          Valve
          Corporation. První vydání hry společností Sierra Studios v roce 1998 bylo určené pro PC s operačním systémem
          Microsoft Windows. Hra byla později vydána také pro herní konzole PlayStation 2 a v lednu 2013 pro operační
          systémy Linux a Mac OS X. Herní engine hry pro Windows se nazývá GoldSource a je založen na engine hry Quake
          od
          společnosti id Software, jenž byl ale pro hru Half-Life velmi upravený a navíc používal i části kódu v tu dobu
          novějšího engine id Tech 2 pro hru Quake 2.
          Hře byly kritiky vytýkány především mnohé skriptované části a celková prezentace. Hra ale získala mnohá
          ocenění
          od
          herních kritiků i samotných hráčů a byla mnohými herními časopisy po celém světě vyhlášena jako akční hra roku
          či
          dokonce nejlepší hra všech dob. Ke dni 16. listopadu 2004 bylo prodáno osm milionů kopií a v prosinci 2008 to
          bylo
          už 9,3 milionu kopií.
              </div>
          </div>
          <div class="col d-flex " data-aos="fade-left">
            <img class="rounded fixed-bottom pull-right" src="imgs/gordon_hl1.png" width="250px">
          </div>

        </div>
        </div>
      </div>
      <div class="m-5">
      <div class="container" >
      <div class=" card bg-dark text-white">
        <h1 class="text-center">Half-Life</h1>
        <div class="row">
        <div class="col-md-6">
          <div class="m-3">
            <p><strong>Maja Miletich </strong> Děj se odehrává někdy mezi lety 1998 až 1999 v pouštích Nového Mexika ve výzkumném komplexu Black Mesa, který
              se v
              mnoha ohledech velmi podobá skutečnému výzkumnému centru Los Alamos a oblasti 51. Hlavní postavou hry je
              Gordon
              Freeman, sedmadvacetiletý teoretický fyzik, absolvent MIT. Freeman je povolán jako experimentátor k pokusu pro
              vytvoření teleportu pomocí nalezeného mimozemského krystalu. Tento pokus se ale vymkne kontrole, zničí velkou
              část
              Black Mesa a zabije mnoho lidí. Výsledkem nepovedeného pokusu je tzv. resonanční kaskáda (fiktivní jev) a po
              celé
              Zemi jsou vytvořeny teleporty, kterými se ale nekontrolovatelně přemisťují mimozemské bytosti z dimenze Xen.
              Freeman, jako jeden z přeživších, se musí pomocí palných zbraní, energetických zbraní nebo páčidla dostat přes
              radiací zamořené komplexy Black Mesa a otevřené vojenské prostory do dimenze Xen a zničit Nihilantha – mozek
              mimozemské armády nepřátelských organismů. Ve hře čas od času uvidí tajemného muže v obleku – G-Mana. Ten
              udělá v
              závěru hry Gordonovi zajímavou nabídku.</p>
              </div>
          </div>
          <div class="col-md-6">
            <img class="" src="imgs/gordon_hl1.png" width="250px">
          </div>

        </div>
        </div>
      </div>
      </div>
    
</html>