<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
  <title>Document</title>
  <script src="js_library/jquery-3.6.0.js"></script>
  <script src="js_library/scrollie/jquery.scrollie.min.js"></script>
  <script src="https://unpkg.com/aos@2.3.1/dist/aos.js" defer></script>
  <script>
    window.onload = () => {
      AOS.init({
        delay: 100, // values from 0 to 3000, with step 50ms
        duration: 1000,// values from 0 to 3000, with step 50ms
        offset: 50
      });
    };
  </script>
  <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
</head>