<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
  <title>Spsei-Life</title>
  <script src="js_library/jquery-3.6.0.js"></script>
  <script src="bootstrap/js/bootstrap.min.js"></script>
</head>