<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    #myBtn {
      transition: 0.4s;
      display: none;
      position: fixed;
      bottom: 20px;
      right: 10px;
      z-index: 99;
      font-size: 18px;
      border: none;
      outline: none;
      background-color: #ff864ee1;
      color: white;
      cursor: pointer;
      padding: 15px;
      border-radius: 4px;
    }

    #myBtn:hover {
      transition: 0.4s;
      background-color: #555;
    }
  </style>
</head>

<body>

  <button   onclick="topFunction()" id="myBtn" title="Zpět nahoru">▲</button>


  <script>
    var mybutton = document.getElementById("myBtn");

    window.onscroll = function() {
      scrollFunction()
    };

    function scrollFunction() {
      if (document.body.scrollTop > 700 || document.documentElement.scrollTop > 700) {
        mybutton.style.display = "block";
      } else {
        mybutton.style.display = "none";
      }
    }


    function topFunction() {
      document.body.scrollTop = 0;
      document.documentElement.scrollTop = 0;
    }
  </script>

</body>

</html>