<div class="main">
    <div id="pozadi">
        <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
        <h1>Half-Life: Alyx</h1>
        <div class="obdelnik">
            <div class="prvni" data-aos="fade-right">
                <h2>Co říká Wikipedie</h2>

                Half-Life: Alyx je střílečka z pohledu první osoby pro virtuální realitu (VR) pro rok 2020 vyvinutá a publikovaná
                společností Valve. Byl vydán pro Windows a Linux s podporou většiny PC kompatibilních VR headsetů. Odehrávající se pět let
                před Half-Life 2 (2004) hráči ovládají Alyx Vance na misi, jejímž cílem je zmocnit se superzbraně patřící mimozemskému
                Combine. Stejně jako předchozí hry Half-Life zahrnuje Alyx boj, hádanky, průzkum a horor o přežití. Hráči používají VR k
                interakci s prostředím a bojují s nepřáteli, pomocí „gravitačních rukavic“ chytají předměty na dálku, podobně jako
                gravitační pistole z Half-Life 2.
                Předchozí hra Half-Life, Episode Two, byla vydána v roce 2007 a skončila jako cliffhanger. Společnost Valve se několikrát
                pokusila vyvinout další hry Half-Life, ale nedokázala se usadit ve směru a její plochá struktura řízení ztěžovala projektům
                nabrat na síle. V polovině roku 2010 začalo Valve experimentovat s VR a v roce 2016 vydalo The Lab, kolekci miniher pro VR.
                Rozpoznali poptávku po velké hře pro VR a experimentovali s prototypy využívajícími jejich různé intelektuální vlastnosti,
                jako je Portal, a zjistili že Half-Life nejlépe vyhovoval VR.
            </div>
            <div class="img_r" data-aos="fade-left">
                <img src="imgs/HlAalyx.jpg" alt="gordon_freeman" class="img_fadel">
            </div>
        </div>
        <div class="obdelnik">
            <div class="prvni" data-aos="fade-right">

                Half-Life: Alyx vstoupil do výroby pomocí nového enginu Source 2 od Valve v roce 2016, s největším týmem v historii Valve,
                včetně členů Campo Santo, studia Valve získané v roce 2018. VR ovlivnila téměř každý aspekt designu, včetně boje, pohybu ,
                design úrovní a tempo. Valve původně plánovalo spuštění Alyx spolu s náhlavní soupravou Index VR v roce 2019, ale odložilo
                to po interní zpětné vazbě na příběh od nového spisovatele Roba Yescomba; Erik Wolpaw a Jay Pinkerton se znovu připojili k
                Valve, aby jej přepsali.
                Half-Life: Alyx získal uznání za svou grafiku, hlasové hraní, vyprávění a atmosféru a byl uváděn jako první zabijácká aplikace
                VR. Byl nominován na řadu ocenění a získal „Nejlepší VR/AR“ na 2020 Game Awards. V den vydání přilákala velký počet hráčů ve
                srovnání s jinými hrami VR, i když Valve uznalo, že publikum VR bylo omezené. Prezident Valve Gabe Newell popsal Alyx jako
                dlouhodobou investici do nových technologií.
            </div>
            <div class="img_r" data-aos="fade-left">
                <img src="imgs/halflife_alyx_wallpaper.jpg" alt="gordon_freeman" class="img_fadel">
            </div>
        </div>
        <h1>Gameplay</h1>
        <div class="obdelnik reverse">
            <div class="img_fader" data-aos="fade-right">
                <img src="imgs/Alyx_hands.jpg" alt="resonance_cascade" class="img_fader">
            </div>
            <div class="druhy" data-aos="fade-left">
                Half-Life: Alyx je hra pro virtuální realitu (VR), která podporuje všechny VR náhlavní soupravy kompatibilní se SteamVR,
                které zahrnují Valve Index, HTC Vive, Oculus Rift, Oculus Quest a všechny náhlavní soupravy Windows Mixed Reality.
                Jelikož byla hra navržena pro VR, Valve řeklo, že nemá žádné plány na verzi bez VR. Half-Life: Alyx také podporuje uživatelské
                mody prostřednictvím Steam Workshop.
                <br>
                <br>
                Hráči ovládají členku Resistance Alyx Vance, zatímco ona a její otec Eli Vance bojují proti Combine, mimozemské říši,
                která dobyla Zemi. Designér David Speyrer řekl, že Alyx nebyla epizodická hra nebo vedlejší příběh, ale „další část příběhu
                Half-Life“, přibližně stejně dlouhá jako Half-Life 2.
            </div>
        </div>
        <div class="obdelnik">
            <div class="prvni" data-aos="fade-right">

                Hráči používají VR k získávání zásob, používání rozhraní, házení předmětů a zapojení do boje. Stejně jako gravitační pistole
                z Half-Life 2, gravitační rukavice umožňují hráčům zvedat předměty na dálku. Hra obsahuje tradiční prvky Half-Life, jako je
                průzkum, hádanky, boj a příběh. I když je hra primárně střílečkou z pohledu první osoby, přidává prvky žánru survival horor,
                protože zdraví a munice jsou vzácnější a zahrnuje děsivá setkání.
                <br>
                <br>
                Hráči se mohou fyzicky pohybovat v měřítku místnosti a pohybovat Alyx ve hře. Případně mohou pomocí analogových pák na ovladačích VR
                pohybovat Alyx jako v tradiční hře, teleportovat se do blízkých bodů nebo používat přechodný režim k „klouzání“ k vybraným bodům. Když se
                hráči teleportují, hra simuluje pohyb, i když je akce okamžitá. Alyx může zemřít, pokud je napadena nebo přesunuta z příliš velké výšky.
            </div>
            <div class="img_r" data-aos="fade-left">
                <img src="imgs/AlyxGloves.jpg" alt="gordon_freeman" class="img_fadel">
            </div>
        </div>
        <h1>Děj</h1>
        <div class="obdelnik reverse">
            <div class="img_fader" data-aos="fade-right">
                <img src="imgs/hlaCombines.jpg" alt="resonance_cascade" class="img_fader">
            </div>
            <div class="druhy" data-aos="fade-left">

                Half-Life: Alyx se odehrává pět let před událostmi Half-Life 2. Zemi dobyli mimozemští Combine, kteří zavedli brutální policejní
                stát. Ve Městě 17 kradou dospívající Alyx a její otec Dr. Eli Vance, oba členové lidského hnutí odporu, zdroje Combine. Poté,
                co je zajme Combine, člen odporu Russell zachrání Alyx a varuje ji, že Eli bude převezen na Nova Prospekt k výslechu. Aby Alyx
                zadržela vlak převážející Eli, vydá se do karanténní zóny, oblasti uvnitř města 17 zamořené parazitickým mimozemským životem.
                Cestou potká excentrického Vortigaunta jménem Gary, který žádá Alyx, aby zachránila jeho kolegy Vortigaunty, a předvídá, že
                Eli zemře.
                V karanténní zóně Alyx vykolejí vlak a Gary zachrání Eli z trosek. Ve vazbě se Eli dozvěděl, že Combine uchovává superzbraň v masivním
                trezoru, který se vznáší nad karanténní zónou; instruuje Alyx, aby našla trezor a ukradla jeho obsah. Alyx se vydává přes karanténní zónu a
                bojuje s mimozemšťany a vojáky Combine. Vypne elektrárnu, která udržuje trezor nad vodou, a zjišťuje, že každá stanice obsahuje zotročené
                Vortigaunty nucené nasměrovat svou energii do trezoru. Vortigaunt, kterou zachrání, slibuje, že on a ostatní zlikvidují zbývající elektrárny.


            </div>
        </div>
        <div class="obdelnik reverse">
            <div class="img_fader" data-aos="fade-right">
                <img src="imgs/halflife_alyx_combat.jpg" alt="resonance_cascade" class="img_fader">
            </div>
            <div class="druhy" data-aos="fade-left">
                Eli kontaktuje Alyx a varuje ji, že trezor neobsahuje zbraň; je to vězení postavené kolem bytového komplexu, aby obsahovalo něco,
                co Combine objevil. Alyx, Eli a Russell uvažují, že cokoli je uvnitř, jim může pomoci v boji s Combine. Když se blíží k trezoru,
                Alyx zaslechne, jak vědec zmiňuje nadřízeným Combine, že okupant přežil incident v Black Mesa. Za předpokladu, že přeživší je
                Gordon Freeman, Alyx se zaměří na záchranu a rozbije trezor na zem.
                <br>
                <br>
                Uvnitř trezoru Alyx najde bytový komplex, kolem kterého byl postaven. Stavbou prostupují anomální fyzikální jevy; předměty se vznášejí v
                antigravitaci a zrcadlové místnosti jsou naskládány jedna na druhou. Alyx objeví v jejím středu pokročilou vězeňskou celu. Rozbije ho a
                očekává, že najde Freemana, ale místo toho vydá tajemného G-Mana.
            </div>
        </div>
        <div class="obdelnik reverse">
            <div class="img_fader" data-aos="fade-right">
                <img src="imgs/hlaGman.jpg" alt="resonance_cascade" class="img_fader">
            </div>
            <div class="druhy" data-aos="fade-left">
            Za odměnu G-Man nabízí své služby Alyx. Žádá, aby odstranil Combine ze Země, ale G-Man to zdůrazňuje
                tato žádost by byla v rozporu se zájmy jeho „zaměstnavatelů“. Místo toho ji přenese do budoucnosti a nabídne jí
                šance změnit výsledek Eliho smrti rukou poradce Combine na konci Half-Life 2: Episode Two. Alyx
                vyhoví, zabije poradkyni a zachrání jejího otce. G-Man informuje Alyx, že dokázala, že je schopná nahradit
                Freeman, se kterým G-Man začal být nespokojený. Uvězní Alyx ve stázi a odejde.
                <br>
                <br>
                Gordon nabude vědomí v základně Bílého lesa odboje. Eli je naživu, ale Alyx chybí. Eli si uvědomuje, co se stalo
                Alyx prohlásí svůj záměr zabít G-Mana a předá Gordonovi jeho páčidlo.
            </div>
        </div>


    </div>
</div>
</div>