
  <script src="js_library/index.js"></script>
  <div class="header">

    <div id="logo_media">
      <a href="index.php" class="logo"><img id="logo" src="imgs/spsei.svg" alt="logo"></a>
    </div>
    <div class="burger" onclick="funkce_burger(this)">
      <div class="bar1"></div>
      <div class="bar2"></div>
      <div class="bar3"></div>
    </div>
    <div class="header-left">
      <nav id="odkazy">
        <div>
        <a class="btn" href="index.php">Domů</a>
        <a class="btn" href="half-life.php">Half-Life</a>
        <a class="btn" href="#Half-Life">Half-Life 2</a>
        <a class="btn" href="#Half-Life">Half-Life 2 epizoda 1</a>
        <a class="btn" href="#Half-Life">Half-Life 2 epizoda 2</a>
        <a class="btn" href="#Half-Life">Half-Life: Alyx</a>
      </div>
        <div id="prihlaseni">
          <a id="prihlas" class="btn" href="prihlasitSe.php">Přihlásit se</a>
          <a id="registr" class="btn" href="registrujSe.php">Registrovat se</a>
        </div>
      </nav>
      
    </div>
  </div>