
  <script src="js_library/index.js"></script>
  <div class="header">

    <div id="logo_media">
      <a href="index.php" class="logo"><img id="logo" src="imgs/spsei.svg" alt="logo"></a>
    </div>
    <div class="burger" onclick="funkce_burger(this)">
      <div class="bar1"></div>
      <div class="bar2"></div>
      <div class="bar3"></div>
    </div>
    <div class="header-left">
      <nav id="odkazy">
        <div>
        <a class="btn" href="index.php">Domů</a>
        <a class="btn" href="half-life.php">Half-Life</a>
        <a class="btn" href="half-life2.php">Half-Life 2</a>
        <a class="btn" href="half-life-episode1.php">Half-Life 2 epizoda 1</a>
        <a class="btn" href="#Half-Life">Half-Life 2 epizoda 2</a>
        <a class="btn" href="#Half-Life">Half-Life: Alyx</a>
      </div>
      <div id="prihlaseni">
      <?php
    if(!isset($_SESSION["user"]))
    {
      echo '
      <a id="prihlas" class="btn" href="prihlasitSe.php">Přihlásit se</a>
      <a id="registr" class="btn" href="registrujSe.php">Registrovat se</a> ';
      echo' <a  class="btn" href="user.php"><img src="https://cdn-icons-png.flaticon.com/512/1946/1946429.png	" alt="userIcon" id="icon"></a>';
    }
    if(isset($_SESSION["user"]))
    {
      echo '<a  class="btn" href="forum.php">Fórum</a>';
      echo' <a  class="btn" href="user.php"><img src="'.$_SESSION['user']['Profile_Img'].'" alt="userIcon" id="icon"></a>';
    }
    ?>
    </div>
      </nav>
      
    </div>
  </div>