<section class="vh-100 gradient-custom">
  <img id="background" src="imgs/spsei.svg" alt="">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card text-black">
          <div id="color">
            <div class="card-body p-5 text-center">
              <a href="index.php" class="logo"> <img id="logo" src="imgs/spsei.svg" alt=""> </a>
              <div class="mb-md-5 mt-md-4 pb-5">
                <h2 class="fw-bold mb-2 text-uppercase">Registrace</h2>
                <form method="post" action="">
                  <div class="form-outline form-white mb-4">
                    <input type="email" required name="email" id="typeEmailX" class="form-control form-control-lg" />
                    <label class="form-label" for="typeEmailX">Email</label>
                  </div>

                  <div class="form-outline form-white mb-4">
                    <input type="text" required name="uname" maxlength="10" id="text" class="form-control form-control-lg" />
                    <label class="form-label" for="typeEmailX">Uživatelské jméno</label>
                  </div>

                  <div class="form-outline form-white mb-4">
                    <input type="password" required name="passwd" id="typePasswordX" class="form-control form-control-lg" />
                    <label class="form-label" for="typePasswordX">Heslo</label>
                  </div>

                  <div class="form-outline form-white mb-4">
                    <input type="password" required name="passwdpotvrzeni" id="PasswordXAcept" class="form-control form-control-lg" />
                    <label class="form-label" for="typePasswordX">Potvrďte heslo</label>
                  </div>
                  <button class="btn btn-outline-dark btn-lg px-5 text-black" type="submit">Zaregistrovat se</button>
              </div>

              </form>

              <div>
                <script>
                  document.write('<a href="' + document.referrer + '">Vrátit se zpět</a>');
                </script>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>