<link rel="stylesheet" href="csss/user.css">
<link rel="stylesheet" href="csss/forum.css">
<h1>Fórum</h1>

<div class="content"> 
<?php
if(!isset($_POST['novy']))
{
echo'<form  method="post" >
    <input type="hidden" value="novy" name="odhlasit">
    <input type="submit" name="novy" value="Nový">
    </form>';
}
if(isset($_POST['novy']))
{
echo '<div class="obdelnik"><div class="content"> <form method="POST">
<label for="postContent">Napište nový příspěvek</label><br>
<div class="content">
<input type="text" name="title">
</div>
<textarea id="postContent" name="postContent" maxlength="10000"></textarea>
<div class="content">
<input type="submit" name="submit">
</div>
</form></div>';
}

if(isset($_POST['submit']))
{
    require "php_universal_functions/functions.php";
    require "php_universal_functions/dbPripojeni.php";  
    
}
?>

</div>
</div>