
<h1>Fórum</h1>

<div class="content"> 
<?php
    require "php_universal_functions/functions.php";
    require "php_universal_functions/dbPripojeni.php";  
    require "forum_functions.php";  
if(!isset($_POST['novy']))
{
echo'<form  method="post" >
    <input type="hidden" value="novy" name="odhlasit">
    <input type="submit" name="novy" value="Nový Příspěvek">
    </form>
    </br>';
}
if(isset($_POST['novy']))
{
echo '<div class="obdelnik"><div class="content"> <form method="POST">
<label >Napište nový příspěvek</label><br>
<div class="content">
<label >Nadpis</label><br>
<input type="text" required maxlength="20" name="title">
</div>
<textarea id="postContent" required name="postContent" maxlength="2000"></textarea>
<div class="content">
<input type="submit" name="submit">
</div>
<div class="content">
<a href="forum.php">Zrušit vytváření příspěvku</a>
</div>
</form></div>
</div>';

}
if(isset($_POST['submit']))
{
    savePost($db,$_POST);
    header('Location: forum.php ');
}
$posts=getPosts($db);
if(isset($_POST['Pid']))
{
    deletePost($db,$_POST['Pid']);
    header('Location:forum.php');
}
foreach($posts as $post)
{
    $user=getUser($db,$post);
    echo '<div class="post obdelnik">
<div class="content lefttop">
<img id="icon" src="'.$user['Profile_Img'].'" alt="">
<h3>'.$user['name'].'</h3>
</div>
<div class="titleCon">
<h2> '.$post['title'].'</h2>

<div class="post content">
'.$post['content'].'
</div>
</br>
</br>
</br>
</br>';
if(isset($_SESSION["admin"]))
{
    echo'<form  method="post" >
    <input type="hidden" value="'.$post["Pid"].'"  name="Pid">
    <input  type="submit" name="smazat" value="Smazat" >
    </form>
    </br>';
}

echo '<div class="date">'.date("j.n.Y",strtotime($post['createdT'])).'</div>
</div>
</div>';
}

?>
</div>

