<script src="forgotPasswd.js"></script>
<section class="vh-100 gradient-custom">
  <img id="background" src="imgs/spsei.svg" alt="">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card  text-black">
          <div id="color">
            <div class="card-body p-5 text-center">
              <a href="index.php" class="logo"> <img id="logo" src="imgs/spsei.svg" alt=""> </a>
              <form method="post" action="">
                <div class="mb-md-5 mt-md-4 pb-5">

                  <h2 class="fw-bold mb-2 text-uppercase">Přihlášení</h2>
                  <p class="text-secondary mb-5">Prosím zadejte svůj Email a heslo</p>

                  <div class="form-outline form-white mb-4">
                    <input type="text" required name="p_EmailOrName" id="typeEmailX" class="form-control form-control-lg" />
                    <label class="form-label" for="typeEmailX">Email nebo uživatelské jméno</label>
                  </div>

                  <div class="form-outline form-white mb-4">
                    <input type="password" required name="p_passwd" id="typePasswordX" class="form-control form-control-lg" />
                    <label class="form-label" for="typePasswordX">Heslo</label>
                  </div>

                  <p class="small mb-5 pb-lg-2" class="text-secondary" onclick="function_alert('Tak to mas blbe')" style="cursor: pointer;">Zapoměli jste heslo?</p>

                  <button class="btn btn-outline-dark btn-lg px-5 text-black" type="submit">Přihlásit se</button>
              </form>
              <div class="d-flex justify-content-center text-center mt-4 pt-1">
                <a href="#!" class="text-white"><i class="fab fa-facebook-f fa-lg"></i></a>
                <a href="#!" class="text-white"><i class="fab fa-twitter fa-lg mx-4 px-2"></i></a>
                <a href="#!" class="text-white"><i class="fab fa-google fa-lg"></i></a>
              </div>
            </div>
            <div>
              <script>
                document.write('<a href="' + document.referrer + '">Vrátit se zpět</a>');
              </script>
            </div>
            <div>
              <p class="mb-0">Nemáte účet? <a href="registrujSe.php" class="text-warning fw-bold">Zaregistrujte se</a>
              </p>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>