<div class="main">
  <div id="pozadi">

    <h1>Half-Life</h1>
    <div class="obdelnik">
      <div class="prvni" data-aos="fade-right">
        <h2>Co říká Wikipedie</h2>
        Half-Life (graficky znázorněno jako HλLF-LIFE) je akční počítačová hra ve stylu sci-fi FPS, vyvinutá firmou
        Valve
        Corporation. První vydání hry společností Sierra Studios v roce 1998 bylo určené pro PC s operačním systémem
        Microsoft Windows. Hra byla později vydána také pro herní konzole PlayStation 2 a v lednu 2013 pro operační
        systémy Linux a Mac OS X. Herní engine hry pro Windows se nazývá GoldSource a je založen na engine hry Quake
        od
        společnosti id Software, jenž byl ale pro hru Half-Life velmi upravený a navíc používal i části kódu v tu dobu
        novějšího engine id Tech 2 pro hru Quake 2.
        Hře byly kritiky vytýkány především mnohé skriptované části a celková prezentace. Hra ale získala mnohá
        ocenění
        od
        herních kritiků i samotných hráčů a byla mnohými herními časopisy po celém světě vyhlášena jako akční hra roku
        či
        dokonce nejlepší hra všech dob. Ke dni 16. listopadu 2004 bylo prodáno osm milionů kopií a v prosinci 2008 to
        bylo
        už 9,3 milionu kopií.
      </div>
      <div class="img_r" data-aos="fade-left">
        <img src="imgs/gordon_hl1.png" alt="gordon_freeman" class="img_fadel">
      </div>
    </div>

    <h1>Děj</h1>
    <div class="obdelnik reverse">
      <div class="img_fader" data-aos="fade-right">
        <img src="imgs/resonance_cascad.jpg" alt="resonance_cascade" class="img_fader">
      </div>
      <div class="druhy" data-aos="fade-left">

        Děj se odehrává někdy mezi lety 1998 až 1999 v pouštích Nového Mexika ve výzkumném komplexu Black Mesa, který
        se v
        mnoha ohledech velmi podobá skutečnému výzkumnému centru Los Alamos a oblasti 51. Hlavní postavou hry je
        Gordon
        Freeman, sedmadvacetiletý teoretický fyzik, absolvent MIT. Freeman je povolán jako experimentátor k pokusu pro
        vytvoření teleportu pomocí nalezeného mimozemského krystalu. Tento pokus se ale vymkne kontrole, zničí velkou
        část
        Black Mesa a zabije mnoho lidí. Výsledkem nepovedeného pokusu je tzv. resonanční kaskáda (fiktivní jev) a po
        celé
        Zemi jsou vytvořeny teleporty, kterými se ale nekontrolovatelně přemisťují mimozemské bytosti z dimenze Xen.
        Freeman, jako jeden z přeživších, se musí pomocí palných zbraní, energetických zbraní nebo páčidla dostat přes
        radiací zamořené komplexy Black Mesa a otevřené vojenské prostory do dimenze Xen a zničit Nihilantha – mozek
        mimozemské armády nepřátelských organismů. Ve hře čas od času uvidí tajemného muže v obleku – G-Mana. Ten
        udělá v
        závěru hry Gordonovi zajímavou nabídku.

      </div>
    </div>
    <h1>Datadisky</h1>
    <div class="obdelnik">
      <div class="prvni" data-aos="fade-right">
        <h2>Half-Life: Opposing Force</h2>
        Half-Life: Opposing Force je prvním datadiskem pro Half-Life, vyvíjený společností Gearbox a vydaný 1.
        listopadu 1999. Opposing Force byl oznámený jako Mission pack (balík misí) pro Half-Life v dubnu 1999 a vyšel
        pro Windows verzi hry. Opposing Force byl přijímán kladně kritikou, a mnozí ukazovali, že přidávání datadisků
        se stává běžné pro celý žánr FPS. Hra vyhrála titul Počítačová hra roku 2000 od Akademie Interaktivních umění
        a Věd.
        <h2>Děj</h2>
        Hlavním hrdinou je Adrian Shephard, příslušník elitní jednotky Mariňáků. Při hraní datadisku se hráč ocitne v
        kůži vojáka HECU (Hazardous Environment Containment Unit, organizace podléhající Americké armádě podobně jako
        např. Delta Force nebo Navy Seals), který byl vládou poslán, aby vzniklý problém "vyřešil". Vojáci vše řeší
        prostým "vyčištěním" celého komplexu s důrazem na eliminaci všech přeživších organismů. Poté se dozvídá, že
        mariňáci s mimozemskými silami ze světa Xen prohrávají a mají se stáhnout. Snaží se tedy ze základny utéct.
        Během hry prochází ve stejném čase stejnými lokacemi jako Gordon Freeman v původní hře, přesto však občas vidí
        věci z poněkud odlišné perspektivy. Během hry dokonce Freemana i zahlédne. Hlavní nepřítel je také tzv. Black
        Ops, elitní jednotka poslána neznámo kým, aby celou oblast zajistila. Ti přitom neváhají zabíjet kohokoliv,
        mariňáky nevyjímaje. Přeživší sekuriťák odhaluje Shephardovi, že Black Ops chtějí odpálit v základně jadernou
        bombu a zabít vše živé uvnitř. Portálem chce také projít masivní mimozemský červ, Shephard ho zbraněnmi
        přinutí projít zpět skrz červí díru.
      </div>
      <div class="img_r" data-aos="fade-left">
        <img src="imgs/Adrian.png" alt="Adrian" class="img_fadel" id="adrian_shepord">
      </div>
    </div>

    <div class="obdelnik reverse">
      <div class="img_fader" data-aos="fade-right">
        <img src="imgs/barney.png" alt="barney" class="img_fader" id="barney">
      </div>
      <div class="druhy" data-aos="fade-left">
        <h2>Half-Life: Blue Shift</h2>
        Half-Life: Blue Shift je druhý datadisk pro Half-Life, vyvíjený společností Gearbox a vydaný firmou Sierra
        Entertainment v roce 2001. Hra byla původně určena jako rozšíření pro Dreamcast verzi Half-Life. Ale tento
        projekt byl ukončen a Blue Shift byl místo toho vydán na Windows 12. června 2001. Kritika hru přijímala
        smíšeně nebo pozitivně, přičemž si recenzenti vychvalovali atmosféru hry a přidání High
        Definition packu, na druhou stranu kritizovali nedostatek novinek a kratší herní dobu.
        <h2>Děj</h2>
        Datadisk hráče postavil do role člena ochranky Barneyho Calhouna, který se, podobně jako Freeman, chce
        zachránit a uniknout z nebezpečných prostor Black Mesa. Po nástupu do služby je Calhoun vyzván, aby pomáhal
        při opravě nefunkčního výtahu. Ovšem po experimentu a objevení portálů se zřítí výtahem do hlubin Black Mesa.
        Calhoun poté osvobodí dr. Rosenberga ze zajetí mariňáků. Dr. Rosenberg s jeho kolegy plánuje uniknout ze
        zařízení pomocí teleportu.
      </div>
    </div>
    <div class="obdelnik">
      <div class="prvni" data-aos="fade-right">
        <h2>Half-Life: Decay</h2>
        Je to třetí rozšiřující balíček pro Half-Life a stejně jako jeho předchůdci se Decay vrací do prostředí a
        časové osy původního příběhu, i když vykresluje příběh z pohledu jiné skupiny protagonistů: dvou vědkyň pracujících v
        Black Mesa. Výzkumné zařízení. Decay je kooperativní hra pro více hráčů navržená tak, aby ji mohli hrát dva lidé, kteří
        společně procházejí úrovněmi hry.
        Decay nebyl kritickým úspěchem, ale byl přijat s určitou pozitivitou novináři videoher. Mnoho recenzentů se domnívalo, že hraní hry s
        kamarádem je zábavné, ale její více puzzle orientovaná hra poněkud ubírala na celkovém zážitku. Řada recenzí uváděla, že hra prostě vypadala
        jako něco víc než další doplněk pro PlayStation 2 verzi Half-Life.
        <h2>Děj</h2>
        V Decay se hráči ujímají role dvou lékařek Colette Green a Giny Cross, které analyzují anomální materiály a vzorky získaných z Xen v
        předchozích teleportačních experimentech. Cross a Green jsou přiřazeni, aby pomohli připravit experiment pro Gordona Freemana. Lékařky pracují
        se dvěma významnými členy vědeckého týmu, Dr. Richardem Kellerem a Dr. Rosenbergem, kteří se po invazi rozhodnou požádat o vojenskou pomoc.
        Armádě je však nařízeno pozabíjet i všechny zaměstnance. Chtějí tedy utěsnit dimenzionální trhlinu a zastavit invazi a dostanou za úkol připravit
        na vypuštění satelit. Satelit má společně s pozemním zařízením napomoci výraznému oslabení účinků rezonanční kaskády. Lékařky mají aktivovat
        krystalový maják, který přes satelit může být schopen utěsnit dimenzionální trhlinu.
        V odemykatelné misi hráč ovládá dva Vortigaunty, kteří vojákům z auta ukradnou oranžové krystaly.
      </div>
      <div class="img_r" data-aos="fade-left">
        <img src="imgs/hlDecay.png" alt="Adrian" class="img_fadel" id="adrian_shepord">
      </div>
    </div>
  </div>
</div>