<div class="main">
  <div id="pozadi">

    <h1>Half-Life 2</h1>
    
    <div class="obdelnik">
      <div class="prvni" data-aos="fade-right">
        <h2>Co říká Wikipedie</h2>
        Stejně jako jeho předchůdce obdržela hra Half-Life 2 od všech kritiků pozitivní ohlas.
        Na hře byly pozitivně hodnoceny vlastnosti jako pokročilá fyzika věcí, animace, zvuk, umělá inteligence,
        grafika a příběh. Hra vyhrála 39 ocenění „Hra roku“ a v několika publikacích byla označena jako „Hra dekády“.
        Přes 6,5 milionu prodaných kusů, do 3. prosince 2008, dělá ze hry jednu z nejlépe prodávaných her historie (toto číslo
        neobsahuje prodeje přes Steam). Hru vlastní zhruba 11 milionů lidí.
        <h2>Gameplay</h2>
        Half-Life 2 je, stejně jako jeho předchůdce Half-Life, first-person shooter, rozdělený do kapitol,
        v nichž se hráč ujímá Gordona Freemana. Hra používá stejné mechanismy jako jeho předchůdce: neustálé
        střídání prostředí, postupné přibývání zbraní a také drobné hádanky, založené na fyzikálním enginu.
        Hráč také začíná bez jakéhokoliv předmětu a pomalu, díky postupu ve hře, sbírá arzenál nutný pro boj.
        Podobné je také chování nepřátel: někteří spolupracují ve skupinách, někteří létají, někteří jsou ozbrojení,
        někteří využívají různých charakteristických pohybů a někteří jenom číhají. Hráč je může zabíjet přímo
        (pomocí zbraní), nebo nepřímo pomocí prostředí (shodit auto na nepřátele, zapálit plyn, pustit elektřinu
        ) a nebo pomocí výbušných barelů. Hra využívá detailní simulaci fyzikálních jevů. Díky tomu jsou ve hře použity
        drobné hádanky založené na fyzikálních jevech, které jsou na rozdíl od prvního dílu (ve kterém jsou použity hádanky,
        jejichž řešením bylo správné nastavení tlačítek) založeny na posunování a přemisťování věcí. Řešení hádanek
        bylo většinou založeno na hmotnosti, velikosti a vztlaku věcí. Například na začátku hry je hráč nucen
        poskládat bedny, aby po nich mohl vyskákat do okna, jenž je umístěno několik metrů nad zemí.Hra nemá cutscény,
        ani žádné další formální zobrazení příběhu. Místo toho je hráč nucen sledovat různé stopy a vodítka,
        která mu pomůžou pochopit situaci. Hodně z chybějícího spojení mezi prvním a druhým dílem je možno vyčíst
        z rozhovoru s hlavními postavami.
      </div>
      <div class="img_r" data-aos="fade-left">
        <img src="imgs/gordon_hl2.png" alt="gordon_freeman" class="img_fadel">
      </div>
    </div>
    <div class="">
    <div class="obdelnik reverse">
      <div class="img_fader" data-aos="fade-right">
        <img src="imgs/city17.png" alt="resonance_cascade" class="img_fader">
      </div>
      <div class="druhy" data-aos="fade-left">
        <h2>Inovace</h2>
        První byl vylepšený HEV oblek obohacen o nové možnosti, přičemž nyní kromě poskytování protijedu při
        otravě či ochraně v podmínkách nehostinných pro život a světla poskytoval také možnosti krátkodobého sprintu,
        kdy Gordonova kondice byla podporována energií (která se ve speciálních článcích po určité době sama dobíjí).
        Později v updatu byl také obohacen zoomem, který ale, kvůli absenci možnosti střelby, nebyl příliš využit.
        Hlavní změnou druhého dílu ovšem byla přítomnost fyzikálního enginu, který byl v době vydání (a vlastně i nyní je)
        považován za jeden z nejzdařilejších. Designéři Valve (v čele s hlavním mozkem a mluvčím Gabe Newell) totiž dokázali
        hru navrhnout tak, aby hráč fyzikální engine využívat musel. Tato změna je asi stejně podstatná jako vzájemné krytí
        nepřátel v díle prvním. Některé hádanky byly na využití gravitace přímo postaveny, většinou šlo však o velice
        jednoduché úkony, které po několika sekundách přemýšlení udeřily do očí. Co se umělé inteligence nepřátel týče,
        společně například s Far Cry patří k nejlepším, co je v počítačových hrách k vidění, ani zde tedy Valve svou
        laťku nesnížili. Nepřátelé se účinně kryjí, snaží se hráče všelijak obejít a přelstít, i nepřátelská fauna
        se chová velice inteligentně (i když pudově).

      </div>
    </div>
    </div>
 
    <h1>Děj</h1>
   
    <div class="obdelnik">
      <div class="prvni" data-aos="fade-right">
        Half-Life 2 se odehrává přibližně dvacet let po incidentu v Black Mesa Research Facility z první hry,
        ve kterém vědci omylem otevřeli portál do nepřátelské dimenze Xen. Hra začíná tím, že Gordon Freeman
        je probuzen ze stagnace tajemným G-Manem, který odhalí, že incident v Black Mesa přitáhl pozornost
        multidimenzionálního impéria zvaného Combine, které dobylo Zemi za sedm hodin. Combine zavedli brutální
        policejní stát biologickou asimilací lidí a jiných druhů. G-Man vloží Gordona do vlaku přijíždějícího do
        města 17, místa citadely Combine, kde jako loutkový vládce Combine vládne Dr. Wallace Breen, bývalý správce
        Black Mesa, který vyjednal kapitulaci Země.Poté, co unikl Combine silám, se Gordon připojí k
        odboji vedenému bývalým vědcem z Black Mesa Dr. Eli Vanceem, jehož součástí je také Vanceova dcera Alyx, bývalý
        strážce Black Mesa Barney Calhoun, který pracuje v utajení jako důstojník civilní ochrany, a další vědec z Black Mesa , Dr. Isaac Kleiner.
      </div>

      <div class="img_r" data-aos="fade-left">
        <img src="imgs/HalfLife2Dej.jpg" alt="Adrian" class="img_fadel" id="adrian_shepord">
      </div>
    </div>
    <div class="obdelnik">
      <div class="prvni" data-aos="fade-right">
        Po neúspěšném pokusu teleportovat se na základnu odporu, Black Mesa East, z Kleinerovy provizorní laboratoře,
        Gordon postupuje pěšky systémem městských kanálů. Pokus o teleportaci náhodně upozorní Breena a Combine na Freemanův
        návrat, což vede k tomu, že pošlou síly, aby na něj zaútočily. Získá vzduchový člun a probojovává se stokami a řekami.
        V Black Mesa East je Gordon znovu představen Eli a setkává se s dalším vědcem odporu, Dr. Judith Mossmanovou.
        Alyx představí Gordonovi svého mazlíčka, robota Psa, a dá mu gravitační pistoli, nástroj, který dokáže manipulovat
        s velkými předměty. Když je základna napadena jednotkami Combine, Eli a Mossman jsou zajati a převezeni do vazebního
        zařízení Combine Nova Prospekt. Gordon, oddělený od Alyx, obchází město Ravenholm zamořené zombie s pomocí jeho posledního
        přeživšího, otce Grigoriho. Při útěku z města Gordon objeví základnu odporu. Používá upravenou dunovou buginu k cestě po
        rozpadající se pobřežní silnici na Nova Prospekt, bojuje proti mimozemským mravencům a pomáhá odboji odrazit nájezdy Combine.
        Gordon vtrhne na Nova Prospekt a znovu se shledá s Alyx. Najdou Eli, ale zjistí, že Mossman je informátor Combine. Než ji mohou
        zastavit, Mossman teleportuje sebe a Eli zpět do Citadely City 17. 
      </div>
      <div class="img_r" data-aos="fade-left">
        <img src="imgs/half-life_2_ravenholm.png" alt="Adrian" class="img_fadel" id="adrian_shepord">
      </div>
    </div>
    <div class="obdelnik">
      <div class="prvni" data-aos="fade-right">
      Kombinovaný teleport exploduje chvíli poté, co jej Gordon a
        Alyx použijí k úniku z Nova Prospektu.
Po návratu do Kleinerovy laboratoře se Gordon a Alyx dozvídají, že teleport selhal a že uplynul týden. V jejich nepřítomnosti
 se proti Combine zmobilizoval odpor. S pomocí Doga a Barneyho se Gordon probojovává do Citadely. Bezpečnostní systém neúmyslně
  přebije Gordonovu gravitační pistoli, což mu umožní probojovat se nahoru do Citadely.
  Gordon je zachycen v transportním modulu Combine a převezen do Breeniny kanceláře, kde on a Mossman čekají s Eli a Alyx v zajetí.
   Breen vysvětluje své plány na další dobývání lidstva pomocí Combine, v rozporu s tím, co řekl Mossmanovi. Rozzlobený Mossman
    osvobodí Gordona, Alyx a Eli, než je Breen může teleportovat mimo svět. Breen se snaží uniknout teleportem, ale Gordon zničí
     jeho reaktor energetickými koulemi vypuštěnými z gravitační pistole, čímž Breena zabije. Právě když reaktor exploduje, G-Man
      se znovu objeví a zmrazí čas. Chválí Gordonovu práci a zmiňuje nabídky na Gordonovy „služby“, než ho uvede zpět do stáze.

      </div>
      <div class="img_r" data-aos="fade-left">
        <img src="imgs/darkEnnergz.png" alt="Adrian" class="img_fadel" id="adrian_shepord">
      </div>
    </div>
    <div >
    <h1>Vývoj</h1>
    <div class="obdelnik reverse">
      <div class="img_fader" data-aos="fade-right">
        <img src="imgs/gaben.jpg" alt="barney" class="img_fader" >
      </div>
      <div class="druhy" data-aos="fade-left">
      Vývoj Half-Life 2 začal v červnu 1999, šest měsíců po vydání původního Half-Life. Byl vyvinut týmem 82.
       S hlasovými herci je toto číslo 100. Prezident Valve, Gabe Newell, chtěl redefinovat žánr FPS a řekl:
        "Proč trávit čtyři roky svého života budováním něčeho, co není inovativní a v podstatě zbytečné? Pokud Half-Life
         2 není považován za nejlepší PC hru všech dob Většinu kluků v tomto týmu to úplně naštve.“Newell svému týmu
          nedal žádný termín a „prakticky neomezený“ rozpočet a slíbil, že v případě potřeby bude projekt financovat sám.
           Hra byla postavena s novým vlastním herním enginem společnosti Valve, Source, vyvinutým současně.
           <br>
           <br>
Zatímco Half-Life byl zasazen do jediného místa, výzkumného zařízení Black Mesa, Valve chtělo „mnohem epičtější a 
globálnější pocit“ pro pokračování. Jedna koncepce spočívala v tom, že se hráč teleportoval mezi planetami, což bylo 
vyřazeno, protože by to ztěžovalo kontinuitu mezi úrovněmi. Na návrh bulharského uměleckého ředitele Viktora Antonova 
se tým usadil ve městě ve východní Evropě. V tomto raném konceptu by hráči začali hru naloděním na Borealis, ledoborec 
mířící do města. Nova Prospekt byla koncipována jako malé železniční depo postavené na starém vězení v pustině a 
vyrostlo ze zastávky do samotného cíle.
<br>
           <br>
Poté, co tým sledoval, jak se hráči spojili s vedlejšími postavami v Half-Life, vyvinul charakterizaci s podrobnějšími 
modely postav a realistickou animací. Animátor Ken Birdwell studoval práci psychologa Paula Ekmana, který zkoumal, jak 
obličejové svaly vyjadřují emoce. Spisovatel Marc Laidlaw vytvořil rodinné vztahy mezi postavami a řekl, že jde o 
„základní dramatickou jednotku, které každý rozumí“, která se ve hrách používá jen zřídka.
<br>
           <br>
Tým integroval fyzikální engine Havok, který simuluje fyziku ve skutečném světě, aby posílil hráčský pocit
 přítomnosti a vytvořil novou hratelnost. Pro experiment vytvořil tým minihru, Zombie Basketball, ve které hráči
  používali zbraň manipulující s fyzikou k házení zombíků skrz obruče. V polovině roku 2001, aby otestoval engine,
   Valve postavilo pouliční válku mezi bouřícími se občany a policií, která zahrnovala tanky, Molotovovy koktejly,
    osobní boje a rabování. Designér John Guthrie to popsal jako „první pokus o získání něčeho – čehokoli – ve hře,
     která používala nehráčské postavy a fyziku“.
      </div>
    </div>
    <div class="obdelnik reverse">
      <div class="img_fader" data-aos="fade-right">
        <img src="imgs/Valve_Lobby_2016.jpg" alt="barney" class="img_fader" >
      </div>
      <div class="druhy" data-aos="fade-left">
      Koncem roku 2001 začala společnost Valve vytvářet showreel v naději, že ji předvede na E3 2002.
       Několik měsíců nechal Newell tým pracovat bez jeho přispění, aby mohl poskytnout nezaujatou zpětnou vazbu,
        a soustředil se na vývoj Steamu, připravované digitální distribuční služby Valve. Tým představil showreel Newellovi,
         předvedl fyziku, prostředí, jako je Borealis, a scénu plnou dialogů s vědeckou postavou Dr. Kleinerem. Newell měl pocit,
          že showreel dostatečně neukázal, jak by fyzika ovlivnila hratelnost a že Kleinerova scéna byla příliš dlouhá. Laidlaw se
           zamyslel nad neúspěchem a řekl: „Dramatické scény s postavami jsou důležité, ale musí sloužit interaktivitě a hratelnosti.“
           <br>
           <br>
V září 2002 tým dokončil druhý showreel, který obsahoval závod buggy podél pobřeží City 17, setkání s headcraby na molu, mimozemský strider
 útočící na město a značně zkrácenou Kleinerovu sekvenci. V říjnu Newell řekl týmu, že oznámí Half-Life 2 na E3 2003 a vydají ho do konce roku.
 Stejně jako u původního Half-Life se tým rozdělil na „kabaly“ pracující na různých úrovních. Designéři vytvořili úrovně pomocí zástupných tvarů a
  povrchů, na kterých pak umělci pracovali.
      </div>
    </div>

  </div>
</div>