
<div class="main">
  <div id="pozadi">

    <h1>Half-Life 2</h1>
    <div class="obdelnik">
      <div class="prvni" data-aos="fade-right">
        <h2>Co říká Wikipedie</h2>
        Stejně jako jeho předchůdce obdržela hra Half-Life 2 od všech kritiků pozitivní ohlas.
        Na hře byly pozitivně hodnoceny vlastnosti jako pokročilá fyzika věcí, animace, zvuk, umělá inteligence,
        grafika a příběh. Hra vyhrála 39 ocenění „Hra roku“ a v několika publikacích byla označena jako „Hra dekády“.
        Přes 6,5 milionu prodaných kusů, do 3. prosince 2008, dělá ze hry jednu z nejlépe prodávaných her historie (toto číslo
        neobsahuje prodeje přes Steam). Hru vlastní zhruba 11 milionů lidí.
        <h2>Gameplay</h2>
        Half-Life 2 je, stejně jako jeho předchůdce Half-Life, first-person shooter, rozdělený do kapitol,
        v nichž se hráč ujímá Gordona Freemana. Hra používá stejné mechanismy jako jeho předchůdce: neustálé
        střídání prostředí, postupné přibývání zbraní a také drobné hádanky, založené na fyzikálním enginu.
        Hráč také začíná bez jakéhokoliv předmětu a pomalu, díky postupu ve hře, sbírá arzenál nutný pro boj.
        Podobné je také chování nepřátel: někteří spolupracují ve skupinách, někteří létají, někteří jsou ozbrojení,
        někteří využívají různých charakteristických pohybů a někteří jenom číhají. Hráč je může zabíjet přímo
        (pomocí zbraní), nebo nepřímo pomocí prostředí (shodit auto na nepřátele, zapálit plyn, pustit elektřinu
        ) a nebo pomocí výbušných barelů. Hra využívá detailní simulaci fyzikálních jevů. Díky tomu jsou ve hře použity
        drobné hádanky založené na fyzikálních jevech, které jsou na rozdíl od prvního dílu (ve kterém jsou použity hádanky,
        jejichž řešením bylo správné nastavení tlačítek) založeny na posunování a přemisťování věcí. Řešení hádanek
        bylo většinou založeno na hmotnosti, velikosti a vztlaku věcí. Například na začátku hry je hráč nucen
        poskládat bedny, aby po nich mohl vyskákat do okna, jenž je umístěno několik metrů nad zemí.Hra nemá cutscény,
        ani žádné další formální zobrazení příběhu. Místo toho je hráč nucen sledovat různé stopy a vodítka,
        která mu pomůžou pochopit situaci. Hodně z chybějícího spojení mezi prvním a druhým dílem je možno vyčíst
        z rozhovoru s hlavními postavami.
      </div>
      <div class="img_r" data-aos="fade-left">
        <img src="imgs/gordon_hl2.png" alt="gordon_freeman" class="img_fadel">
      </div>
    </div>

    <div class="obdelnik">
      <div class="img_fader" data-aos="fade-right">
        <img src="imgs/city17.png" alt="resonance_cascade" class="img_fader">
      </div>
      <div class="druhy" data-aos="fade-left">
        <h2>Inovace</h2>
        První byl vylepšený HEV oblek obohacen o nové možnosti, přičemž nyní kromě poskytování protijedu při
        otravě či ochraně v podmínkách nehostinných pro život a světla poskytoval také možnosti krátkodobého sprintu,
        kdy Gordonova kondice byla podporována energií (která se ve speciálních článcích po určité době sama dobíjí).
        Později v updatu byl také obohacen zoomem, který ale, kvůli absenci možnosti střelby, nebyl příliš využit.
        Hlavní změnou druhého dílu ovšem byla přítomnost fyzikálního enginu, který byl v době vydání (a vlastně i nyní je)
        považován za jeden z nejzdařilejších. Designéři Valve (v čele s hlavním mozkem a mluvčím Gabe Newell) totiž dokázali
        hru navrhnout tak, aby hráč fyzikální engine využívat musel. Tato změna je asi stejně podstatná jako vzájemné krytí
        nepřátel v díle prvním. Některé hádanky byly na využití gravitace přímo postaveny, většinou šlo však o velice
        jednoduché úkony, které po několika sekundách přemýšlení udeřily do očí. Co se umělé inteligence nepřátel týče,
        společně například s Far Cry patří k nejlepším, co je v počítačových hrách k vidění, ani zde tedy Valve svou
        laťku nesnížili. Nepřátelé se účinně kryjí, snaží se hráče všelijak obejít a přelstít, i nepřátelská fauna
        se chová velice inteligentně (i když pudově).

      </div>
    </div>

    <div class="obdelnik">
      <div class="prvni" data-aos="fade-right">
        <h2>Děj</h2>
        Half-Life 2 se odehrává přibližně dvacet let po incidentu v Black Mesa Research Facility z první hry,
        ve kterém vědci omylem otevřeli portál do nepřátelské dimenze Xen. Hra začíná tím, že Gordon Freeman
        je probuzen ze stagnace tajemným G-Manem, který odhalí, že incident v Black Mesa přitáhl pozornost
        multidimenzionálního impéria zvaného Combine, které dobylo Zemi za sedm hodin. Combine zavedli brutální
        policejní stát biologickou asimilací lidí a jiných druhů. G-Man vloží Gordona do vlaku přijíždějícího do
        města 17, místa citadely Combine, kde jako loutkový vládce Combine vládne Dr. Wallace Breen, bývalý správce
        Black Mesa, který vyjednal kapitulaci Země.Poté, co unikl Combine silám, se Gordon připojí k
        odboji vedenému bývalým vědcem z Black Mesa Dr. Eli Vanceem, jehož součástí je také Vanceova dcera Alyx, bývalý
        <?php
        if (!isset($_POST['novy'])) {
          echo '<form  method="post" >
    <input type="hidden" value="novy" name="odhlasit">
    <input type="submit" name="novy" value="Nový Příspěvek">
    </form>
    </br>';
        }
        ?>
      </div>
      <?php

      ?>
      <div class="img_r" data-aos="fade-left">
        <img src="imgs/HalfLife2Dej.jpg" alt="Adrian" class="img_fadel" id="adrian_shepord">
      </div>
    </div>
    <div class="obdelnik">
      <div class="img_fader" data-aos="fade-right">
        <img src="imgs/barney.png" alt="barney" class="img_fader" id="barney">
      </div>
      <div class="druhy" data-aos="fade-left">
        <h2>Half-Life: Blue Shift</h2>
        Half-Life: Blue Shift je druhý datadisk pro Half-Life, vyvíjený společností Gearbox a vydaný firmou Sierra
        Entertainment v roce 2001. Hra byla původně určena jako rozšíření pro Dreamcast verzi Half-Life. Ale tento
        projekt byl ukončen a Blue Shift byl místo toho vydán na Windows 12. června 2001. Kritika hru přijímala
        smíšeně nebo pozitivně, přičemž si recenzenti vychvalovali atmosféru hry a přidání High
        Definition packu, na druhou stranu kritizovali nedostatek novinek a kratší herní dobu.
        <h2>Děj</h2>
        Datadisk hráče postavil do role člena ochranky Barneyho Calhouna, který se, podobně jako Freeman, chce
        zachránit a uniknout z nebezpečných prostor Black Mesa. Po nástupu do služby je Calhoun vyzván, aby pomáhal
        při opravě nefunkčního výtahu. Ovšem po experimentu a objevení portálů se zřítí výtahem do hlubin Black Mesa.
        Calhoun poté osvobodí dr. Rosenberga ze zajetí mariňáků. Dr. Rosenberg s jeho kolegy plánuje uniknout ze
        zařízení pomocí teleportu.
      </div>
    </div>
  </div>
</div>