<div class="main">
    <div id="pozadi">
        <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
        <h1>Half-Life</h1>
        <div class="obdelnik">
            <div class="prvni" data-aos="fade-right">
                <h2>Co říká Wikipedie</h2>

                Half-Life 2: Episode One Pokračuje v příběhu Half-Life 2 (2004); jako vědec Gordon Freeman musí hráči uniknout z města 17 s
                Gordonovou společnicí Alyx Vance. Stejně jako předchozí hry Half-Life, Episode One kombinuje střílení, hádanky a vyprávění příběhů.
                Po šestiletém vývoji Half-Life 2 Valve přešlo na epizodický vývoj v naději, že bude vydávat hry častěji. Pro Episode One se zaměřili na vývoj
                postavy Alyx a rozšířili její umělou inteligenci. Využívá aktualizovanou verzi enginu Valve's Source s novou technologií osvětlení a animací.
                Episode One obdržel převážně pozitivní recenze; kooperativní hra s Alyx získala zvláštní chválu, ačkoli krátká délka byla kritizována.
                To bylo portováno na Xbox 360 a PlayStation 3 jako součást kompilace The Orange Box z roku 2007. Druhá epizoda následovala v roce 2007.
            </div>
            <div class="img_r" data-aos="fade-left">
                <img src="imgs/alyx.png" alt="gordon_freeman" class="img_fadel">
            </div>
        </div>

        <h1>Děj</h1>
        <div class="obdelnik reverse">
            <div class="img_fader" data-aos="fade-right">
                <img src="imgs/hl2e1w.jpg" alt="resonance_cascade" class="img_fader">
            </div>
            <div class="druhy" data-aos="fade-left">

                Ve městě 17 Gordon Freeman a jeho spojenkyně Alyx Vanceová zničili reaktor v srdci Combine Citadel. Když exploduje,
                G-Man zasáhne a vytáhne Gordona. Objeví se několik Vortigauntů a zachrání Alyx před výbuchem. Vortigaunti se objeví před G-Manem
                a postaví se mezi něj a Gordona. Teleportují Gordona pryč ze scény, čímž omezují účinek G-Manových schopností na Gordona.
                Alyxin mazlíček robot Dog získá Gordona z trosek před Citadelou a Gordon se znovu shledá s Alyx. Alyx kontaktuje svého otce Eli Vance a
                vědce Isaaca Kleinera, kteří utekli z města. Kleiner jim říká, že jádro Citadely brzy exploduje, což zcela vyhladí Město 17. 
                <br>
           <br>
           Alyx a Gordon
                znovu vstoupí do Citadely a dočasně jádro stabilizují. Alyx zjistí, že vojáci Combine Elite urychlují zničení Citadely, aby poslali
                „přenosový paket“ do domovského světa Combine. Stáhne si kopii zprávy spolu s přenosem od Dr. Judith Mossmanové, ve kterém se zmiňuje o
                „projektu“, který našla, než ji přeruší útok Combine.
            </div>
        </div>
        <div class="obdelnik reverse">
            <div class="img_fader" data-aos="fade-right">
                <img src="imgs/hl2e1strider.jpg" alt="resonance_cascade" class="img_fader">
            </div>
            <div class="druhy" data-aos="fade-left">
                Alyx a Gordon nastoupí do vlaku, aby unikli z Citadely, ale ten vykolejí. Postupují pěšky v ulicích města, bojují s
                neorganizovanými jednotkami Combine a nekontrolovatelnými mimozemskými zamořeními. Setkávají se s Barneym Calhounem a
                skupinou dalších přeživších, kteří se připravují na přesun na vlakové nádraží, aby unikli z města 17.
                <br>
           <br>
            Alyx a Gordon vedou a
                doprovázejí přeživší na stanici, protože cesta tam je neustále zahlcena a sabotována jednotkami Combine.
                Alyx a Gordon vyjedou z města 17 jiným vlakem a uniknou právě ve chvíli, kdy reaktor vybuchne a zpráva Combine se přenese.
                Několik raketových modulů obsahujících Combine Advisors startuje z Citadely, když detonuje. Výsledná rázová vlna vykolejí vlak.
            </div>
        </div>
        
        </div>
    </div>
</div>