<div class="main">
    <div id="pozadi">
        <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
        <h1>Half-Life 2: Episode Two</h1>
        <div class="obdelnik">
            <div class="prvni" data-aos="fade-right">
                <h2>Co říká Wikipedie</h2>

                Half-Life 2: Episode Two Po Episode One (2006) je to druhá ze dvou kratších epizodických her, které pokračují v příběhu
                Half-Life 2 (2004). Hráči ovládají Gordona Freemana, který se svou spojenkyní Alyx Vance cestuje přes hory obklopující Město
                17 na základnu odporu. Stejně jako předchozí hry v sérii, Episode Two kombinuje střílení, řešení hádanek a narativní prvky,
                ale přidává rozsáhlá prostředí a méně lineární sekvence.
                Episode Two byla vydána v roce 2007 pro Windows na distribuční službě Steam společnosti Valve a jako součást The Orange Box, kompilace her
                Valve pro Xbox 360 a PlayStation 3. Verzi pro PlayStation vyrobila společnost Electronic Arts. Episode Two získal pozitivní recenze.
                Třetí epizoda Half-Life 2 byla oznámena na Vánoce 2007, ale byla zrušena, protože Valve opustilo vývoj epizod. V roce 2020, po zrušení
                několika dalších Half-Life projektů, Valve vydalo Half-Life: Alyx.
            </div>
            <div class="img_r" data-aos="fade-left">
                <img src="imgs/half-life2e2.jpg" alt="gordon_freeman" class="img_fadel">
            </div>
        </div>

        <h1>Děj</h1>
        <div class="obdelnik reverse">
            <div class="img_fader" data-aos="fade-right">
                <img src="imgs/hl2e2Citadela.jpg" alt="resonance_cascade" class="img_fader">
            </div>
            <div class="druhy" data-aos="fade-left">

                Combine, multidimenzionální impérium, které si zotročilo Zemi, využilo zničení své Citadely k otevření masivního portálu.
                To jim umožní přivolat posily a zničit Odpor. V horách u Města 17 uniknou bojovníci Odporu Gordon Freeman a Alyx Vance
                troskám vlaku, kterým unikli z města. Na staré vysílací stanici navážou spojení s vědci odporu Dr. Kleinerem a Eli Vancem
                na základně White Forest. Dozvědí se, že Odboj může být schopen zavřít portál pomocí kopie kombinovaného přenosu, který Alyx
                nese.
                V opuštěném dole je Alyx kriticky zraněna Combine Hunterem. Vortigaunt je zavede do podzemního úkrytu odporu. Gordon obnoví
                extrakt larev z blízké kolonie mravenců, nezbytný pro vortigaunty k uzdravení Alyx. Zatímco se vortigaunti zabývají jejím
                léčením, tajemný G-Man kontaktuje Gordona a naznačuje Alyxinu důležitost pro jeho plány; odhalil, že jí zachránil život
                ve výzkumném zařízení Black Mesa navzdory námitkám blíže nespecifikované třetí strany. Instruuje Alyx v bezvědomí, aby
                řekla svému otci, aby se „připravil na nepředvídané následky“.


            </div>
        </div>
        <div class="obdelnik reverse">
            <div class="img_fader" data-aos="fade-right">
                <img src="imgs/hl2e2alyx.jpg" alt="resonance_cascade" class="img_fader">
            </div>
            <div class="druhy" data-aos="fade-left">
                Poté, co se Alyx zotaví, ona a Gordon pokračují ve starém vozidle Odporu, bojují s jednotkami Combine a přežívají setkání s
                Combine Advisorem, vysoce postaveným Combine mimozemšťanem se silnými psychickými schopnostmi. Ve White Forest se znovu
                setkali s Dr. Kleinerem, Eli a Alyxiným mazlíčkem robotem Dogem. Gordon je představen egoistickému Dr. Arne Magnussonovi.
                Vědci připravují raketu, kterou plánují použít s kódem portálu Combine a satelitním polem vypuštěným Gordonem v Black Mesa
                k uzavření portálu Combine.
                <br>
                <br>
                Poté, co Gordon odrazí útok Combine na základnu, Alyx předá Dr. Kleinerovi zprávu od Judith Mossmanové nalezené v Citadele.
                Obsahuje záběry a souřadnice Borealis, výzkumného plavidla Aperture Science postaveného v ledoborec podobném USCGC Healy,
                vysvětluje Kleiner, zmizelo spolu s částí okolního suchého doku. Kleiner trvá na tom, že by měl být použit k podpoře úsilí
                Odporu, zatímco Eli namítá, že je nemožné ho ovládat a musí být zničen. Souhlasí, že Alyx a Gordon pojedou na Borealis a
                pokusí se najít Mossmanovou.
            </div>
        </div>
        <div class="obdelnik reverse">
            <div class="img_fader" data-aos="fade-right">
                <img src="imgs/hl2e2ending.jpg" alt="resonance_cascade" class="img_fader">
            </div>
            <div class="druhy" data-aos="fade-left">
                Alyx nevědomky předá G-Manovu zprávu svému otci, čímž ho znepokojuje. Eli sám s Gordonem odhalí, že to byl G-Man, kdo 
                poskytl testovací vzorek, který způsobil incident v Black Mesa, a že mu pošeptal stejné varování, když Gordon vstoupil do
                 testovací komory. Slibuje, že po uzavření portálu vysvětlí více.
                Zatímco vědci připravují raketu, White Forest se ocitne pod útokem Combine. Gordon zničí útočící Stridery pomocí 
                experimentálních výbušnin vytvořených Magnussonem. Vědci vypustí raketu a zavřou portál, čímž uvězní síly Combine na Zemi.
                 Alyx a Gordon se připravují k odjezdu na Borealis a Eli varuje Gordona před „nákladem“ lodi. Všichni tři míří do hangáru s
                  úmyslem nastoupit do vrtulníku, ale dva poradci vtrhli do hangáru a zadrželi je. Když se je Eli snaží osvobodit, je zabit 
                  jedním z poradců. Když se druhý připravuje zabít Alyx, vtrhne Dog a zažene Poradce pryč. Vzlykající Alyx svírá tělo svého 
                  otce.
            </div>
        </div>


    </div>
</div>
</div>