<script src="js_library/acceptForm.js"></script>

<div class="content">
<?php
require "head.phtml";
echo '
<div id="profile">
<form  method="POST" id="form" enctype="multipart/form-data">
<label for="img" class="upload">
<img id="profile" src="'.$_SESSION["user"]["Profile_Img"].'" alt="">
</label>
<input onchange="submit()" id="img" name="img" type="file" accept="image/png, image/gif, image/jpeg">
</form>
</div>
<br>
<h1>'.$_SESSION["user"]["name"].'</h1>
<div id="informations"> 
'.$_SESSION["user"]["email"].'
<br>
Datum registrace: '.date("j.n.Y",strtotime($_SESSION["user"]["createdT"])).'
</div>';
if(isset($_FILES['img']))
{
 
    $type=explode("/",  $_FILES['img']['type']);
    move_uploaded_file($_FILES['img']["tmp_name"], "imgs/userIcon.".$type[1]."");
    
}
if(isset($_POST["odhlasit"]))
{
    unset($_SESSION["user"]);
    header('Location: index.php');
}
?>
    <form  method="post" action="">
    <input type="hidden" value="odhlasit se" name="odhlasit">
    <input type="submit" value="odhlásit se">
    </form>
</div>
