<div class="content">
<?php
require "head.phtml";
echo '
<div id="profile">
<form action="" name="uploadedfile" method="POST">
<label for="onimg" class="upload">
<img id="profile" src="'.$_SESSION["user"]["Profile_Img"].'" alt="">
</label>
<input onchange="form.submit()" id="img" name="img" type="file" accept="image/png, image/gif, image/jpeg"/>
</form>
</div>
<br>
<h1>'.$_SESSION["user"]["name"].'</h1>
<div id="informations"> 
'.$_SESSION["user"]["email"].'
<br>
Datum registrace: '.$_SESSION["user"]["createdT"].'
</div>';
if(isset($_POST["img"]))
{
    $soubor=$_FILES['img']["tmp_name"];
    echo $soubor;
}
if(isset($_POST["odhlasit"]))
{
    unset($_SESSION["user"]);
    header('Location: index.php');
}
?>

    <form  method="post" action="">
    <input type="hidden" value="odhlasit se" name="odhlasit">
    <input type="submit" value="odhlásit se">
    </form>
</div>
